Decorator to calculate function execution time added
netsil/integrations-core pull request #64
Opened 2021-06-07 19:19 UTC by sheetansh2

- alerts needs to be added for the given criteria.

2021-06-08 03:31 UTC, goswamisandeep commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if int(endTime - initalTime) >= 10:
make 10 a const

2021-06-08 09:15 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if int(endTime - initalTime) >= 10:
ok

2021-06-08 09:31 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if int(endTime - initalTime) >= 10:
done

2021-07-15 10:32 UTC, goswamisandeep requested changes
Solution is incomplete , needs similar changes in dpmAgent

2021-07-15 10:32 UTC, goswamisandeep commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +    def send_alert(self, alert_message, alert_title):
swap title and mssage position

2021-07-15 10:32 UTC, goswamisandeep commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        statsd.event(title = alert_title, text = alert_message, alert_type = ALERT_TYPE_ERROR, tags = tags)
Alert title should be without space e.g NTNX_sqlserver_heartbeat_collection

2021-07-15 10:38 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +    def send_alert(self, alert_message, alert_title):
done

2021-07-19 14:25 UTC, bhowmickatish commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +            send_alert(self, alert_title, alert_message)
do u still need new alert method ... cant u use raise_alert by passing using global_instance

2021-07-19 14:29 UTC, bhowmickatish commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +            global global_endpoint_uuid
if u use raise_alert , global_instance is enough ... global_endpoint_uuid isnt required

2021-07-19 14:31 UTC, bhowmickatish commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +NTNX__db_execution_time_exceeded = "NTNX_db_execution_time_exceeded"
make sure these new alerts r registered in https://github.com/netsil/AOC/blob/master/tools/collectors/aiops/dpm-agent/configs/externalalerts/sqlserver.json

2021-07-20 08:01 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +            send_alert(self, alert_title, alert_message)
Yes It will be needed because this decorator is used by many class whose object(self) is different than raise_alerts's class. So it will be needed.

2021-07-20 08:07 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +            global global_endpoint_uuid
Here we are fetching endpoint using self and instance both, global instance won't be enough as the self can be of different class in which I am using the decorator, E.g: class SqlComplexMetric line number 863,  function fetch_all_values line 874. and also for class SqlSimpleMetric. Here

2021-07-20 08:07 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +NTNX__db_execution_time_exceeded = "NTNX_db_execution_time_exceeded"
On it, will be added in the next commit

2021-07-20 08:23 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +NTNX__db_execution_time_exceeded = "NTNX_db_execution_time_exceeded"
https://github.com/netsil/AOC/pull/9959
done

2021-07-20 11:53 UTC, bhowmickatish commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if global_endpoint_uuid != None:
did u mean to check global_instance here ?

2021-07-20 11:57 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if global_endpoint_uuid != None:
yes, my bad will change it.

2021-07-20 12:00 UTC, sheetansh2 reviewed
new alert added to the sqlserver.json file, decorator added to calculate time

2021-07-20 12:33 UTC, bhowmickatish commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if global_instance != None:
just if global_instance is enough to do None or empty checks

2021-07-20 12:33 UTC, bhowmickatish approved these changes

2021-07-20 14:12 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if global_instance != None:
None check is enough because whenever global_instance is set in the callback function, if the main instance failed then only this will fail and in that case raise_alert function inside the call is also going to fail. So I guess this should suffice.

2021-07-21 04:15 UTC, bhowmickatish commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if global_instance != None:
i wasnt asking ... just saying that u dont need to explicitly do comparison with None ... just using if global_instance does it implicitly. :)

2021-07-21 05:51 UTC, sheetansh2 commented on sqlserver/datadog_checks/sqlserver/sqlserver.py
> +        if global_instance != None:
ohh that, yes yes sure, will make the change right away.

2021-08-27 07:51 UTC, ahalam requested changes
This is not required now. You should close the pull request

2021-08-27 08:42 UTC, sheetansh2 commented
Not required now, closing this PR.

2021-08-27 08:42 UTC, closed without merging